### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by Tyr-Arcana** [orange-games/GA-JavaScript-SDK#2]
The LICENSE file in the root directory says this is licensed under the MIT license, however the code in the dist folder all begins by saying it's released under the "GNUv3" (by which I assume you mean GNU GPL v3) license.

Please can you clarify which license is in effect?
I would request that you opt for one that allows commercial use (without modification) at least, such as MIT or LGPL.

Thank you.

**Comment by AleBles** [comment]
Ha, good find! Everything should/is licenced under MIT. Changed the old references from GNU to MIT, and I'm sorry for the confusion :)
